// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iEWD7iszphyBKHLObDI7Fti5MZv54H0',
    appId: '1:846489060517:android:d904f639ba95aef1d1794c',
    messagingSenderId: '846489060517',
    projectId: 'nguyenquocphi-669bb',
    databaseURL: 'https://nguyenquocphi-669bb-default-rtdb.firebaseio.com',
    storageBucket: 'nguyenquocphi-669bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0euVLguizvdwZnpG6ZfqVfsDitvFeY4c',
    appId: '1:846489060517:ios:ab0f8bbe6845751bd1794c',
    messagingSenderId: '846489060517',
    projectId: 'nguyenquocphi-669bb',
    databaseURL: 'https://nguyenquocphi-669bb-default-rtdb.firebaseio.com',
    storageBucket: 'nguyenquocphi-669bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-Jf26QKrf7wtqI97Kmn8fKB_UhXzjZQ',
    appId: '1:846489060517:web:78ab498ce1dabfdfd1794c',
    messagingSenderId: '846489060517',
    projectId: 'nguyenquocphi-669bb',
    authDomain: 'nguyenquocphi-669bb.firebaseapp.com',
    databaseURL: 'https://nguyenquocphi-669bb-default-rtdb.firebaseio.com',
    storageBucket: 'nguyenquocphi-669bb.firebasestorage.app',
    measurementId: 'G-7W3GBNGM10',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-Jf26QKrf7wtqI97Kmn8fKB_UhXzjZQ',
    appId: '1:846489060517:web:78ab498ce1dabfdfd1794c',
    messagingSenderId: '846489060517',
    projectId: 'nguyenquocphi-669bb',
    authDomain: 'nguyenquocphi-669bb.firebaseapp.com',
    databaseURL: 'https://nguyenquocphi-669bb-default-rtdb.firebaseio.com',
    storageBucket: 'nguyenquocphi-669bb.firebasestorage.app',
    measurementId: 'G-7W3GBNGM10',
  );
}
